-- auto Generated on 2020-06-11
-- DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id VARCHAR (50) NOT NULL COMMENT 'id',
  username VARCHAR (50) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '密码',
  email VARCHAR (50) NOT NULL DEFAULT '' COMMENT '电子邮件',
  phone VARCHAR (50) NOT NULL DEFAULT '' COMMENT '电话号码',
  sex INT (11) NOT NULL DEFAULT -1 COMMENT '性别',
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'users';
